# Copyright 2023 Adevinta

version: 1

project_name: lava

gomod:
  proxy: true

builds:
  - id: lava
    main: ./cmd/lava
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: arm
    mod_timestamp: '{{.CommitTimestamp}}'
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: '{{.ProjectName}}_{{.Os}}_{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}'

release:
  footer: |
    **Full Changelog**: https://github.com/adevinta/lava/compare/{{.PreviousTag}}...{{.Tag}}
  prerelease: auto
